name: bitcoin_ath_bot
description: Bitcoin ATH Bot for open social networks
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  coingecko_api: ^2.0.1
  hive: ^2.2.3
  intl: ^0.19.0
  mason_logger: ^0.3.0
  nostr: ^1.5.0

dev_dependencies:
  very_good_analysis: ^6.0.0

