name: bitcoin_ath_bot
description: Bitcoin ATH Bot for open social networks
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  atproto: ^0.13.3
  bluesky: ^0.18.7
  coingecko_api: ^2.0.1
  hive: ^2.2.3
  intl: ^0.19.0
  mason_logger: ^0.3.0
  mastodon_api:
    git:
      url: https://github.com/MaTeS72/mastodon-api.git
  nostr: ^1.5.0

dev_dependencies:
  very_good_analysis: ^6.0.0
